const animalEmojis = [
    { emoji: '🐶', name: 'Dog' },
    { emoji: '🐱', name: 'Cat' },
    { emoji: '🐭', name: 'Mouse' },
    { emoji: '🐹', name: 'Hamster' },
    { emoji: '🐰', name: 'Rabbit' },
    { emoji: '🦊', name: 'Fox' },
    { emoji: '🐻', name: 'Bear' },
    { emoji: '🐼', name: 'Panda' },
    { emoji: '🐨', name: 'Koala' },
    { emoji: '🐯', name: 'Tiger' },
    { emoji: '🦁', name: 'Lion' },
    { emoji: '🐮', name: 'Cow' },
    { emoji: '🐷', name: 'Pig' },
    { emoji: '🐸', name: 'Frog' },
    { emoji: '🐵', name: 'Monkey' },
    { emoji: '🐔', name: 'Chicken' },
    { emoji: '🐧', name: 'Penguin' },
    { emoji: '🐦', name: 'Bird' },
    { emoji: '🐤', name: 'Chick' },
    { emoji: '🦆', name: 'Duck' },
    { emoji: '🦅', name: 'Eagle' },
    { emoji: '🦉', name: 'Owl' },
    { emoji: '🦇', name: 'Bat' },
    { emoji: '🐺', name: 'Wolf' },
    { emoji: '🐗', name: 'Boar' },
    { emoji: '🐴', name: 'Horse' },
    { emoji: '🦄', name: 'Unicorn' },
    { emoji: '🐝', name: 'Bee' },
    { emoji: '🐛', name: 'Caterpillar' },
    { emoji: '🦋', name: 'Butterfly' },
    { emoji: '🐌', name: 'Snail' },
    { emoji: '🐞', name: 'Lady' },
    { emoji: '🐜', name: 'Ant' },
    { emoji: '🦟', name: 'Mosquito' },
    { emoji: '🦗', name: 'Cricket' },
    { emoji: '🕷️', name: 'Spider' },
    { emoji: '🦂', name: 'Scorpion' },
    { emoji: '🐢', name: 'Turtle' },
    { emoji: '🐍', name: 'Snake' },
    { emoji: '🦎', name: 'Lizard' },
    { emoji: '🦖', name: 'Rex' },
    { emoji: '🦕', name: 'Sauropod' },
    { emoji: '🐙', name: 'Octopus' },
    { emoji: '🦑', name: 'Squid' },
    { emoji: '🦐', name: 'Shrimp' },
    { emoji: '🦞', name: 'Lobster' },
    { emoji: '🦀', name: 'Crab' },
    { emoji: '🐠', name: 'Fish' },
    { emoji: '🐬', name: 'Dolphin' },
    { emoji: '🦈', name: 'Shark' },
    { emoji: '🐳', name: 'Whale' },
    { emoji: '🐊', name: 'Crocodile' },
    { emoji: '🐆', name: 'Leopard' },
    { emoji: '🦓', name: 'Zebra' },
    { emoji: '🦍', name: 'Gorilla' },
    { emoji: '🦧', name: 'Orangutan' },
    { emoji: '🐘', name: 'Elephant' },
    { emoji: '🦛', name: 'Hippopotamus' },
    { emoji: '🦏', name: 'Rhinoceros' },
    { emoji: '🐪', name: 'Camel' },
    { emoji: '🦒', name: 'Giraffe' },
    { emoji: '🦘', name: 'Kangaroo' },
    { emoji: '🐃', name: 'Buffalo' },
    { emoji: '🐂', name: 'Ox' },
    { emoji: '🐄', name: 'Cow' },
    { emoji: '🐎', name: 'Horse' },
    { emoji: '🐖', name: 'Pig' },
    { emoji: '🐏', name: 'Ram' },
    { emoji: '🐑', name: 'Sheep' },
    { emoji: '🐐', name: 'Goat' },
    { emoji: '🦙', name: 'Llama' },
    { emoji: '🦌', name: 'Deer' },
    { emoji: '🐕', name: 'Dog' },
    { emoji: '🐩', name: 'Poodle' },
    { emoji: '🐓', name: 'Rooster' },
    { emoji: '🦃', name: 'Turkey' },
    { emoji: '🦚', name: 'Peacock' },
    { emoji: '🦜', name: 'Parrot' },
    { emoji: '🦢', name: 'Swan' },
    { emoji: '🦩', name: 'Flamingo' },
    { emoji: '🕊️', name: 'Dove' },
    { emoji: '🐇', name: 'Rabbit' },
    { emoji: '🦝', name: 'Raccoon' },
    { emoji: '🦨', name: 'Skunk' },
    { emoji: '🦡', name: 'Badger' },
    { emoji: '🦫', name: 'Beaver' },
    { emoji: '🦦', name: 'Otter' },
    { emoji: '🦥', name: 'Sloth' },
    { emoji: '🐀', name: 'Rat' },
    { emoji: '🐿️', name: 'Chipmunk' },
    { emoji: '🦔', name: 'Hedgehog' },
];

const adjectives = [
    { adjective: 'Brave', emoji: '🔥' },
    { adjective: 'Daring', emoji: '⚡️' },
    { adjective: 'Witty', emoji: '😄' },
    { adjective: 'Clever', emoji: '🧠' },
    { adjective: 'Playful', emoji: '🎉' },
    { adjective: 'Joyful', emoji: '😊' },
    { adjective: 'Energetic', emoji: '💪' },
    { adjective: 'Loyal', emoji: '🐾' },
    { adjective: 'Gracious', emoji: '🌺' },
    { adjective: 'Sassy', emoji: '💁' },
    { adjective: 'Curious', emoji: '🔎' },
    { adjective: 'Elegant', emoji: '👑' },
    { adjective: 'Silly', emoji: '🤪' },
    { adjective: 'Mighty', emoji: '🦾' },
    { adjective: 'Happy', emoji: '😃' },
    { adjective: 'Creative', emoji: '🎨' },
    { adjective: 'Adventurous', emoji: '🌍' },
    { adjective: 'Spirited', emoji: '🌟' },
    { adjective: 'Charming', emoji: '😊' },
    { adjective: 'Enchanting', emoji: '✨' },
    { adjective: 'Radiant', emoji: '☀️' },
    { adjective: 'Fancy', emoji: '🎩' },
    { adjective: 'Magical', emoji: '🔮' },
    { adjective: 'Dreamy', emoji: '💭' },
    { adjective: 'Blissful', emoji: '🌈' },
    { adjective: 'Sparkling', emoji: '✨' },
    { adjective: 'Whimsical', emoji: '🌙' },
    { adjective: 'Delightful', emoji: '😄' },
    { adjective: 'Illusional', emoji: '🌌' },
    { adjective: 'Pink', emoji: '💖' },
];

function getRandomElement(array) {
    const randomIndex = Math.floor(Math.random() * array.length);
    return array[randomIndex];
}

function generatePlayer() {
    const randomAdjective = getRandomElement(adjectives);
    const randomAnimalEmoji = getRandomElement(animalEmojis);
    return {
        name: `${randomAdjective.adjective}${randomAnimalEmoji.name}`,
        emoji: `${randomAdjective.emoji}${randomAnimalEmoji.emoji}`
    }
}

exports.Player = ({
    create: () => generatePlayer()
})
